"""Generate THIRD_PARTY_LICENSES.md from declared dependencies + vendored attribution.

Reads:
- pyproject.toml [project.dependencies] and [project.optional-dependencies.streamlit]
- vendor/<name>/LICENSE + vendor/<name>/UPSTREAM_VERSION

Writes a deterministic THIRD_PARTY_LICENSES.md at repo root. Runs as part of
the release pipeline (release.yml). Idempotent — running twice produces the
same file.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Curated metadata for the project's dependencies. Keep narrow on purpose —
# the dependency set is small enough that manual curation beats trying to
# scrape PyPI metadata at build time.
KNOWN_LICENSES: dict[str, dict[str, str]] = {
    "python-pptx": {
        "license": "MIT",
        "use": "Native .pptx shape and slide rendering.",
        "url": "https://pypi.org/project/python-pptx/",
    },
    "anthropic": {
        "license": "MIT",
        "use": "Claude API client (Streamlit BYO-key path; skill paths use Claude's runtime).",
        "url": "https://pypi.org/project/anthropic/",
    },
    "pyyaml": {
        "license": "MIT",
        "use": "Loading the canonical falsification prompt corpus and runtime defaults.",
        "url": "https://pypi.org/project/PyYAML/",
    },
    "streamlit": {
        "license": "Apache-2.0",
        "use": "Local web app surface (optional).",
        "url": "https://pypi.org/project/streamlit/",
    },
    "pillow": {
        "license": "HPND (BSD-style, MIT-compatible)",
        "use": "PNG composition for the bento gallery snapshot (optional).",
        "url": "https://pypi.org/project/Pillow/",
    },
}


def _load_dependencies() -> tuple[list[str], list[str]]:
    pyproject = (REPO_ROOT / "pyproject.toml").read_bytes()
    data = tomllib.loads(pyproject.decode("utf-8"))
    project = data["project"]
    runtime = list(project.get("dependencies", []))
    streamlit = list(project.get("optional-dependencies", {}).get("streamlit", []))
    return runtime, streamlit


def _normalize_dep(spec: str) -> str:
    """Extract bare package name from a dependency spec string."""
    for sep in (">=", "<=", "==", "~=", "!=", ">", "<", "[", " "):
        if sep in spec:
            spec = spec.split(sep, 1)[0]
    return spec.strip().lower()


def _vendored_attribution(vendor_dir: Path) -> str | None:
    if not vendor_dir.is_dir():
        return None
    license_text = (
        (vendor_dir / "LICENSE").read_text(encoding="utf-8")
        if (vendor_dir / "LICENSE").is_file()
        else "(no LICENSE file present)"
    )
    version_text = (
        (vendor_dir / "UPSTREAM_VERSION").read_text(encoding="utf-8")
        if (vendor_dir / "UPSTREAM_VERSION").is_file()
        else "(no UPSTREAM_VERSION file present)"
    )
    return (
        f"### {vendor_dir.name}\n\n```\n{version_text}\n```\n\nLicense:\n\n```\n{license_text}\n```"
    )


def _format_dep(spec: str, optional: bool = False) -> str:
    name = _normalize_dep(spec)
    meta = KNOWN_LICENSES.get(name)
    if not meta:
        return f"### {name}\n\n- **PyPI:** (lookup needed)\n- **License:** (curate in `scripts/generate_third_party_licenses.py`)\n"
    optional_marker = " (optional)" if optional else ""
    return (
        f"### {name}{optional_marker}\n\n"
        f"- **PyPI:** {meta['url']}\n"
        f"- **License:** {meta['license']}\n"
        f"- **Used for:** {meta['use']}\n"
    )


def build() -> str:
    runtime, streamlit = _load_dependencies()
    parts: list[str] = [
        "# Third-Party Licenses",
        "",
        "This file enumerates every third-party component used by `ia-pptx-generator`, with version, license, and attribution. Maintained per NFR11 of the PRD.",
        "",
        "The project itself is licensed under MIT (see `LICENSE`).",
        "",
        "Generated by `scripts/generate_third_party_licenses.py`. Re-run to regenerate.",
        "",
        "---",
        "",
        "## Vendored",
        "",
    ]
    vendor_dir = REPO_ROOT / "vendor"
    if vendor_dir.is_dir():
        for sub in sorted(vendor_dir.iterdir()):
            if sub.is_dir():
                attribution = _vendored_attribution(sub)
                if attribution:
                    parts.append(attribution)
                    parts.append("")
    parts.extend(["---", "", "## Runtime Python Dependencies", ""])
    for dep in runtime:
        parts.append(_format_dep(dep, optional=False))
    parts.extend(["---", "", "## Optional Dependencies (Streamlit surface)", ""])
    for dep in streamlit:
        parts.append(_format_dep(dep, optional=True))
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    out_path = REPO_ROOT / "THIRD_PARTY_LICENSES.md"
    new_content = build()
    if out_path.is_file() and out_path.read_text(encoding="utf-8") == new_content:
        print("THIRD_PARTY_LICENSES.md is already up to date.")
        return 0
    out_path.write_text(new_content, encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
